package assignment;

/**
 * 
 * Contains the monthly details of the orders placed for a particular menu item.
 * Contains the number of times a particular item was sold and the total revenue generated by each item.
 * @author shuvamnandi
 *
 */
public class SaleStructure 
{
	private int quantity;
	private String name;
	private float price;
	public SaleStructure()
	{
		name=null;
		quantity=0;
		price=0;
	}
	/**
	 * Returns the number of times each menu item was sold in a particular month.
	 * @return quantity
	 */
	public int getQuantity() 
	{
		return quantity;
	}
	/**
	 * Returns the total revenue generated by each menu item.
	 * @return price
	 */
	public float getPrice() 
	{
		return price;
	}
	/**
	 * Returns the name of the menu item.
	 * @return name
	 */
	public String getName() 
	{
		return name;
	}
	/**
	 * Increases the number of times a menu item has been placed by 1, whenever it is found in the order records.
	 */
	public void increaseQuantity() 
	{
		quantity++;
	}
	/**
	 * Sets the name of a particular menu item.
	 * @param n
	 */
	public void setName(String n) 
	{
		name=n;
	}
	/**
	 * Adds to the price variable of a menu item whenever it is found in the order records.
	 * @param amount
	 */
	public void setPrice(float amount) 
	{
		price+=amount;
	}
}
